### ISSUE TITLE
Add additional responsive and regular image styles based on Cliff's list

### ISSUE THREAD

**Issue by thejimbirch** [kanopi/saplings-media#12]
Use https://www.drupal.org/project/easy_responsive_images

Teamwork ticket: https://kanopi.teamwork.com/app/tasks/29431765

Ration needed:

Wide:
21:9
16:9
16:3
5:4
5:2
4:3
3:2
2:1
1:1

Tall:
9:21
9:16
4:5
3:16
3:4
2:5
2:3
1:2

**Comment by taylorwillskanopi** [comment]
PR: https://github.com/kanopi/saplings-media/pull/15

**Comment by thejimbirch** [comment]
#15 closed this.
